# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='media/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
